### ISSUE TITLE
Error in prepare_navpoint_network.py

### ISSUE THREAD

**Issue by ghost** [ELSA-Project/ELSA-ABM#1]
Hi,
I installed ELSA and all it's requirements as stated in the get_started.pdf. After running all tests 4 out of 5 are successful. The other gives me following error:

/usr/lib/python2.7/dist-packages/matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
I attached node 6 with degree 1 to node 17
I attached node 18 with degree 1 to node 0
..The following sectors do not have any navpoint left: [4]
The following sectors do not have any navpoint left: [4]
I add a navpoint at the centroid for them.
I add also some links with the closest points of neighboring sectors.
G.neighbors(sec) [1, 3, 6]
Adding edge between 17 and 16
Adding edge between 17 and 0
Adding edge between 17 and 7
# .E
## ERROR: test_check_everybody_has_one_cc (**main**.TestHighNetworkFunctions)

Traceback (most recent call last):
  File "./test_prepare_navpoint_network.py", line 342, in test_check_everybody_has_one_cc
    self.G, problem = check_everybody_has_one_cc(self.G, repair=False)
  File "../abm_strategic/prepare_navpoint_network.py", line 343, in check_everybody_has_one_cc
    problem_here = len(cc)>1
TypeError: object of type 'generator' has no len()

---

Ran 4 tests in 0.178s

FAILED (errors=1)

Any Ideas how to solve this Issue?

**Comment by GGurtner** [comment]
Hi there,
First, thanks for using the ELSA Simulator :). I looked into your issue and it was a change in the last version of the networkx module which triggered this error, thank you for reporting it. I fixed it and you can now pull the new version.
Cheers.

**Comment by ghost** [comment]
thx for the fix, it works as intended now. I still have 1 problem though. I can't get simulationO.py to run. The assert check_object(G) keeps giving me errors, no matter what I set as G. Could you give a small example on how to set parameter G in the **init** function, 'cause I tried all sorts of things for hours now and it just doesn't work.
Thanks a lot.

**Comment by GGurtner** [comment]
Generally speaking, G should be built with the prepare_navpoint_network.py file, to be compatible with the model. You can run it directly like this `./prepare_navpoint_network.py` and it will build a network based on the template parameter file paras_G.py. You can then modify this template as needed.

**Comment by ghost** [comment]
Ye i figured all of that already. My question was for the specific case of the file simulationO.py. In the constructor def **init**(self, paras, G=None, verbose=True):#, make_dir=False) the description says         G : hybrid network
            compulsory, None is deprecated TODO.
So I can't leave it at default, if I do it gives me an assert Error from following line: assert check_object(G)
I already created a hybrid network and saved it in the results file. My question now is, how do I put my created network into the constructor? Or in other words, what do I set in the constructor to not get an assert Error anymore?

**Comment by GGurtner** [comment]
Ok, so if you do it manually, you just have to load your network from the file and feed it into the constructor:

``` python
# do whatever you need to get G from the file, for instance:
with open(my_file) as f:
    G = pickle.load(f)

# Then call the constructor this way:
sim = Simulation(paras, G=G)
```

Otherwise, you an use some higher-level function, for instance you can call directly `generate_traffic(G)`, which uses the default `paras.py` template to run one simulation. You can change the value of some parameters directly like this: `generate_traffic(G, N=200)`.

Does it help?

**Comment by ghost** [comment]
thanks a lot for your help so far and I hope it doesn't bother you, but sadly I keep running into some Issues i can't resolve(I got no experience on python yet).

The higher-level function worked and also when I use the low-level function I am able to load G into the constructor. Unfortunately I get another error:

When I enter sim = Simulation(paras, G=G), I get the error that paras is not defined, so I set paras using the following:
    paras_file = jn(main_dir, 'abm_strategic', 'paras.py')

```
sim = Simulation(paras=paras_file,G=G)
```

Using that, I get following error:

Traceback (most recent call last):
  File "sim.py", line 23, in <module>
    Simulation(paras=paras_file,G=G)
  File "../../abm_strategic/simulationO.py", line 86, in **init**
    if k in paras.keys():
AttributeError: 'str' object has no attribute 'keys'

**Comment by GGurtner** [comment]
Doing:

``` python
paras_file = jn(main_dir, 'abm_strategic', 'paras.py')
```

only gives you a string, and you need to pass a full Paras object (that's a modified dictionary, but nevermind). To load it from your paras.py file you can use the read_paras function included in the utilities.py file, like this: `paras = read_paras(paras_file=paras_file)`. 

That being said, I would advise you to use generate_traffic if you are not familiar with python, it would be much, much simpler, and it is very versatile. By the way, you can also pass a file path as a string to this function for the parameters, for instance:

``` python
paras_file = jn(main_dir, 'abm_strategic', 'paras.py')
generate_traffic(G, paras_file=paras_file)
```

will work.
